INSERT INTO ref_iwaran_jenis_kes (code, nama, kategori, is_active, created_at, updated_at) VALUES
('001', 'Rayuan', 'mal', 1, NOW(), NOW()),
('002', 'Permohonan Kebenaran Merayu', 'mal', 1, NOW(), NOW()),
('003', 'Semakan', 'mal', 1, NOW(), NOW()),
('004', 'Permohonan Tegahan / Injunksi Membawa Anak Keluar Malaysia', 'mal', 1, NOW(), NOW()),
('005', 'Permohonan Tegahan / Injunksi Terhadap Gangguan', 'mal', 1, NOW(), NOW()),
('006', 'Permohonan Pengesahtarafan Anak', 'mal', 1, NOW(), NOW()),
('007', 'Tuntutan Pengesahan Waqaf', 'mal', 1, NOW(), NOW()),
('008', 'Tuntutan Pengesahan Nazar', 'mal', 1, NOW(), NOW()),
('009', 'Tuntutan Gantirugi Pertunangan', 'mal', 1, NOW(), NOW()),
('010 / 131', 'Permohonan / Tuntutan Pengesahan / Perintah Nikah', 'mal', 1, NOW(), NOW()),
('011 / 113', 'Permohonan / Tuntutan Kebenaran Poligami', 'mal', 1, NOW(), NOW()),
('012', 'Permohonan Perintah Daftar Nikah Poligami', 'mal', 1, NOW(), NOW()),
('013', 'Permohonan Perisytiharan Pembubaran Perkahwinan Sebab Pertukaran Agama', 'mal', 1, NOW(), NOW()),
('014 / 162', 'Tuntutan Fasakh', 'mal', 1, NOW(), NOW()),
('015', 'Permohonan Anggapan Mati', 'mal', 1, NOW(), NOW()),
('016', 'Tuntutan Muta''ah', 'mal', 1, NOW(), NOW()),
('017', 'Tuntutan Harta Sepencarian', 'mal', 1, NOW(), NOW()),
('018', 'Tuntutan Nafkah Isteri', 'mal', 1, NOW(), NOW()),
('019', 'Tuntutan Nafkah Kepada Pihak Tak Upaya', 'mal', 1, NOW(), NOW()),
('020', 'Tuntutan Cagaran Nafkah', 'mal', 1, NOW(), NOW()),
('021', 'Tuntutan Nafkah Eddah', 'mal', 1, NOW(), NOW()),
('022 / 254', 'Tuntutan Mengubah Perintah Nafkah', 'mal', 1, NOW(), NOW()),
('023 / 256', 'Tuntutan Tunggakan Nafkah', 'mal', 1, NOW(), NOW()),
('024 / 251', 'Tuntutan Nafkah Anak', 'mal', 1, NOW(), NOW()),
('025', 'Tuntutan Mengubah Perintah Hak Jagaan Anak / Nafkah Anak', 'mal', 1, NOW(), NOW()),
('026', 'Tuntutan Mengubah Perjanjian Hak Jagaan Anak / Nafkah Anak', 'mal', 1, NOW(), NOW()),
('027', 'Permohonan / Tuntutan Membatalkan Perintah Nafkah', 'mal', 1, NOW(), NOW()),
('028 / 231', 'Tuntuan Hadhanah', 'mal', 1, NOW(), NOW()),
('029', 'Tuntutan Pemecatan Penjaga Anak', 'mal', 1, NOW(), NOW()),
('030', 'Permohonan Perintah Larangan Berkaitan Harta Anak Yang Belum Dewasa', 'mal', 1, NOW(), NOW()),
('031', 'Permohonan Penjaga Anak Yatim', 'mal', 1, NOW(), NOW()),
('032', 'Permohonan Pembekuan Transaksi Harta', 'mal', 1, NOW(), NOW()),
('033', 'Permohonan Penguatkuasaan Perintah Nafkah', 'mal', 1, NOW(), NOW()),
('034', 'Permohonan Perlaksanaan Perintah Mahkamah', 'mal', 1, NOW(), NOW()),
('035', 'Tuntutan Ganishmen / Hiwalah', 'mal', 1, NOW(), NOW()),
('036 / 456', 'Permohonan Perintah Menghina Mahkamah', 'mal', 1, NOW(), NOW()),
('037 / 424', 'Tuntutan Penghutang Penghakiman', 'mal', 1, NOW(), NOW()),
('038', 'Permohonan Perintah Interim', 'mal', 1, NOW(), NOW()),
('039', 'Permohonan Pengesahan Wasiat', 'mal', 1, NOW(), NOW()),
('040 / 311', 'Permohonan Sijil Faraid / Akuan Pusaka', 'mal', 1, NOW(), NOW()),
('041', 'Permohonan Interlokutori', 'mal', 1, NOW(), NOW()),
('042 / 163', 'Permohonan Faraq Nikah', 'mal', 1, NOW(), NOW()),
('043', 'Permohonan Keluar Islam', 'mal', 1, NOW(), NOW()),
('044', 'Permohonan Pengesahan Hibah', 'mal', 1, NOW(), NOW()),
('045', 'Permohonan Pengesahan Hibah Semasa Maradul Maut', 'mal', 1, NOW(), NOW()),
('046 / 313', 'Tuntutan Pengesahan Sabitan Nasab / Ahli Waris', 'mal', 1, NOW(), NOW()),
('047', 'Permohonan Mendakwa / Membela Sebagai Orang Miskin', 'mal', 1, NOW(), NOW()),
('048', 'Permohonan Interplider', 'mal', 1, NOW(), NOW()),
('049', 'Tuntutan Gantirugi Perkahwinan', 'mal', 1, NOW(), NOW()),
('050', 'Permohonan Kebenaran Nikah Bawah Umur', 'mal', 1, NOW(), NOW()),
('051', 'Permohonan Wali Hakim / Am', 'mal', 1, NOW(), NOW()),
('052 / 124', 'Tuntutan Wali Enggan / Engkar', 'mal', 1, NOW(), NOW()),
('053 / 112', 'Permohonan Kebenaran Bernikah Perempuan Yang Bercerai Tanpa Eddah / Janda Berhias', 'mal', 1, NOW(), NOW()),
('054 / 152', 'Tuntutan Pengesahan Lafaz Cerai', 'mal', 1, NOW(), NOW()),
('055 / 151', 'Tuntutan Perceraian', 'mal', 1, NOW(), NOW()),
('056 / 154', 'Tuntutan Khuluk / Tebus Talaq', 'mal', 1, NOW(), NOW()),
('057 / 153', 'Tuntutan Pengesahan Cerai Takliq', 'mal', 1, NOW(), NOW()),
('058 / 143', 'Tuntutan Sabitan Nusyuz', 'mal', 1, NOW(), NOW()),
('059', 'Tuntutan Hak Tempat Tinggal', 'mal', 1, NOW(), NOW()),
('060', 'Tuntutan Perintah Supaya Suami Tinggal Bersama Semula', 'mal', 1, NOW(), NOW()),
('061 / 155', 'Permohonan Pengesahan Rujuk', 'mal', 1, NOW(), NOW()),
('072', 'Tuntutan / Permohonan Penyelesaian/ Penjelasan Hutang Simati', 'mal', 1, NOW(), NOW()),
('073', 'Perintah Penyitaan Dan Penjualan', 'mal', 1, NOW(), NOW()),
('074 / 416', 'Perintah Pengkomitan-Pelaksanaan Penghakiman Bagi Penyerahan Anak', 'mal', 1, NOW(), NOW()),
('075 / 415', 'Perintah Pengkomitan-Penguatkuasaan Penghakiman Untuk Menahan Diri Dari Melakukan Sesuatu Perbuatan', 'mal', 1, NOW(), NOW()),
('076 / 425', 'Notis Penghakiman', 'mal', 1, NOW(), NOW()),
('077', 'Permohonan Melanjutkan Tempoh Rayuan', 'mal', 1, NOW(), NOW()),
('078', 'Permohonan Notis Tunjuk Sebab', 'mal', 1, NOW(), NOW()),
('079', 'Permohonan Pengesahan Eddah', 'mal', 1, NOW(), NOW()),
('080', 'Permohonan Memulakan Prosiding Baru Bagi Kes-kes Yang Ditarik Balik', 'mal', 1, NOW(), NOW()),
('081', 'Permohonan Taksiran Kos', 'mal', 1, NOW(), NOW()),
('082', 'Permohonan Perintah Bersaling', 'mal', 1, NOW(), NOW()),
('099', 'Lain-lain', 'mal', 1, NOW(), NOW()),
('101', 'Rayuan', 'jenayah', 1, NOW(), NOW()),
('102', 'Permohonan Kebenaran Merayu', 'jenayah', 1, NOW(), NOW()),
('103', 'Semakan', 'jenayah', 1, NOW(), NOW()),
('104 / 611', 'Pemujaan Salah', 'jenayah', 1, NOW(), NOW()),
('105 / 612', 'Mendakwa Bukan Islam', 'jenayah', 1, NOW(), NOW()),
('106 / 613', 'Takfir', 'jenayah', 1, NOW(), NOW()),
('107 / 614', 'Doktrin Palsu', 'jenayah', 1, NOW(), NOW()),
('108 / 615', 'Dakwaan Palsu', 'jenayah', 1, NOW(), NOW()),
('109 / 633', 'Menyebarkan Pendapat Bertentangan Dengan Fatwa', 'jenayah', 1, NOW(), NOW()),
('110 / 634', 'Mengingkari Perintah Mahkamah', 'jenayah', 1, NOW(), NOW()),
('111 / 623', 'Penerbitan Bertentangan Hukum Syarak', 'jenayah', 1, NOW(), NOW()),
('112 / 641', 'Sumbang Mahram', 'jenayah', 1, NOW(), NOW()),
('113 / 643', 'Muncikari', 'jenayah', 1, NOW(), NOW()),
('114 / 647', 'Persediaan Bersetubuh Luar Nikah', 'jenayah', 1, NOW(), NOW()),
('115', 'Hubungan Jenis Sesama Jantina', 'jenayah', 1, NOW(), NOW()),
('116 / 645', 'Persetubuhan Bertentangan Dengan Hukum Tabi''i', 'jenayah', 1, NOW(), NOW()),
('117 / 731', 'Memujuk Lari Perempuan Bersuami', 'jenayah', 1, NOW(), NOW()),
('118 / 733', 'Menghasut Suami Isteri Supaya Bercerai', 'jenayah', 1, NOW(), NOW()),
('119', 'Menjual / Memberikan Anak Kepada Bukan Islam', 'jenayah', 1, NOW(), NOW()),
('120 / 657', 'Qazaf', 'jenayah', 1, NOW(), NOW()),
('121 / 652', 'Liwat', 'jenayah', 1, NOW(), NOW()),
('122 / 653', 'Musahaqah', 'jenayah', 1, NOW(), NOW()),
('123 / 664', 'Mendirikan Masjid / Surau Tanpa Kebenaran', 'jenayah', 1, NOW(), NOW()),
('124', 'Memujuk Lari Orang Perempuan', 'jenayah', 1, NOW(), NOW()),
('125', 'Pecah Amanah', 'jenayah', 1, NOW(), NOW()),
('126', 'Pecah Rahsia', 'jenayah', 1, NOW(), NOW()),
('127', 'Pegawai Mengingkari Arahan Undang-Undang Dengan Niat Hendak Menyebabkan Bencana Kepada Mana-Mana Orang', 'jenayah', 1, NOW(), NOW()),
('128', 'Tidak Mengemukakan Dokumen Kepada Pegawai Agama Di Sisi Undang-Undang Syarak', 'jenayah', 1, NOW(), NOW()),
('129 / 813', 'Enggan Mengangkat Sumpah Yang Dikehendaki Oleh Pegawai Agama', 'jenayah', 1, NOW(), NOW()),
('130 / 814', 'Enggan Menjawab Soalan Pegawai Agama Yang Diberi Kuasa', 'jenayah', 1, NOW(), NOW()),
('131', 'Sengaja Menghina Dan Mengganggu Pegawai Agama Yang Sedang Bersidang Dalam Prosiding Mahkamah', 'jenayah', 1, NOW(), NOW()),
('132 / 655', 'Menggalakkan Maksiat', 'jenayah', 1, NOW(), NOW()),
('133 / 618', 'Mempersendakan Ayat Al-Quran dll', 'jenayah', 1, NOW(), NOW()),
('134 / 621', 'Menghina Agama Islam', 'jenayah', 1, NOW(), NOW()),
('135 / 631', 'Memusnahkan / Mencemarkan Tempat Beribadat', 'jenayah', 1, NOW(), NOW()),
('136 / 632', 'Menghina Pihak Berkuasa Agama', 'jenayah', 1, NOW(), NOW()),
('137 / 622', 'Mengajar Tanpa Tauliah', 'jenayah', 1, NOW(), NOW()),
('138 / 625', 'Berjudi', 'jenayah', 1, NOW(), NOW()),
('139 / 626', 'Minuman Yang Memabukkan', 'jenayah', 1, NOW(), NOW()),
('140 / 661', 'Tidak Membayar Zakat / Fitrah', 'jenayah', 1, NOW(), NOW()),
('141 / 642', 'Pelacuran', 'jenayah', 1, NOW(), NOW()),
('142 / 646', 'Bersetubuh Luar Nikah', 'jenayah', 1, NOW(), NOW()),
('143 / 651', 'Khalwat', 'jenayah', 1, NOW(), NOW()),
('144 / 732', 'Menghalang Suami Isteri Hidup Bersama', 'jenayah', 1, NOW(), NOW()),
('145 / 663', 'Pemungutan Zakat / Fitrah Tanpa Diberi Kuasa', 'jenayah', 1, NOW(), NOW()),
('146 / 673', 'Penyalahgunaan Tanda Halal', 'jenayah', 1, NOW(), NOW()),
('147 / 682', 'Subahat', 'jenayah', 1, NOW(), NOW()),
('148 / 713', 'Gangguan Terhadap Perkahwinan', 'jenayah', 1, NOW(), NOW()),
('149 / 714', 'Akuan Palsu Untuk Berkahwin', 'jenayah', 1, NOW(), NOW()),
('150', 'Tidak Memberikan Keadilan Sewajarnya Kepada Isteri', 'jenayah', 1, NOW(), NOW()),
('151', 'Murtad Untuk Membatalkan Nikah', 'jenayah', 1, NOW(), NOW()),
('152 / 624', 'Menghasut Supaya Mengabai Kewajipan Agama', 'jenayah', 1, NOW(), NOW()),
('153 / 681', 'Percubaan Melakukan Kesalahan Di Bawah UndangUndang Syarak', 'jenayah', 1, NOW(), NOW()),
('154', 'Kesalahan Yang Tidak Ditentukan Hukuman Berkaitan Undang-Undang, Kaedah Dan Peraturan Pentadbiran Undang-Undang Islam', 'jenayah', 1, NOW(), NOW()),
('155', 'Penghinaan Mahkamah', 'jenayah', 1, NOW(), NOW()),
('156', 'Permohonan Jenayah Pelbagai', 'jenayah', 1, NOW(), NOW()),
('157 / 628', 'Tidak Menghormati Ramadan', 'jenayah', 1, NOW(), NOW()),
('158 / 629', 'Tidak Solat Jumaat', 'jenayah', 1, NOW(), NOW()),
('159 / 654', 'Lelaki Berlagak Perempuan', 'jenayah', 1, NOW(), NOW()),
('160 / 656', 'Perbuatan Tidak Sopan Di Tempat Awam', 'jenayah', 1, NOW(), NOW()),
('161 / 711', 'Tidak Hadir Dihadapan Pendaftar NCR', 'jenayah', 1, NOW(), NOW()),
('162', 'Penyelenggaraan Buku Negeri Perakuan Nikah Tak Legal / Tak Mengikut Undang-Undang', 'jenayah', 1, NOW(), NOW()),
('163 / 715', 'Mengakad Nikah Tanpa Kuasa Yang Sah', 'jenayah', 1, NOW(), NOW()),
('164 / 715', 'Kesalahan Berhubung Akad Nikah', 'jenayah', 1, NOW(), NOW()),
('165 / 716', 'Berkahwin Bersalahan Dengan Bahagian Dua UndangUndang Keluarga Islam', 'jenayah', 1, NOW(), NOW()),
('166 / 717', 'Poligami Tanpa Kebenaran Mahkamah', 'jenayah', 1, NOW(), NOW()),
('167 / 721', 'Perceraian Tanpa Kebenaran Mahkamah', 'jenayah', 1, NOW(), NOW()),
('168 / 722', 'Tidak Membuat Laporan Berkaitan Undang-Undang Keluarga Islam', 'jenayah', 1, NOW(), NOW()),
('169', 'Meninggal Langsung Isteri', 'jenayah', 1, NOW(), NOW()),
('170', 'Menganiaya Isteri', 'jenayah', 1, NOW(), NOW()),
('171', 'Isteri Tidak Menurut Perintah (Nusyus)', 'jenayah', 1, NOW(), NOW()),
('172', 'Persetubuhan Luar Nikah Antara Orang-Orang Bercerai', 'jenayah', 1, NOW(), NOW()),
('173', 'Kecuaian Dengan Sengaja Untuk Tidak Mematuhi Perintah Di Bawah Undang-Undang Keluarga Islam', 'jenayah', 1, NOW(), NOW()),
('174', 'Merujuk Tanpa Kebenaran Isteri', 'jenayah', 1, NOW(), NOW()),
('175 / 737', 'Tidak Melaporkan Rujuk', 'jenayah', 1, NOW(), NOW()),
('176', 'Persetubuhan Dalam Tempoh Eddah Raji''e', 'jenayah', 1, NOW(), NOW()),
('177 / 665', 'Memungut Khairat Tanpa Kebenaran', 'jenayah', 1, NOW(), NOW()),
('178', 'Memberi Maklumat / Keterangan Palsu Kepada Pendaftar Muallaf', 'jenayah', 1, NOW(), NOW()),
('179', 'Menceroboh Atau Menduduki Secara Haram Harta Waqaf / Harta Majlis', 'jenayah', 1, NOW(), NOW()),
('180 / 648', 'Hamil Luar Nikah', 'jenayah', 1, NOW(), NOW()),
('181 / 627', 'Membuat Dan Menjual Minuman Yang Memabukkan', 'jenayah', 1, NOW(), NOW()),
('182', 'Tidak Menghiraukan Titah Perintah Mengenai Awal Ramadhan Dan Dua Hari Raya', 'jenayah', 1, NOW(), NOW()),
('183', 'Bertindak Salah Sebagai Imam, Khatib Atau Bilal Dalam Soal Jumaat', 'jenayah', 1, NOW(), NOW()),
('184', 'Memberi Syarahan Dalam Masjid Tanpa Kebenaran', 'jenayah', 1, NOW(), NOW()),
('185', 'Kesalahan-Kesalahan Berkaitan Baitulmal', 'jenayah', 1, NOW(), NOW()),
('186 / 815', 'Enggan Menandatangani Pernyataan', 'jenayah', 1, NOW(), NOW()),
('187', 'Beramal Sebagai Peguam Syarie Tanpa Tauliah', 'jenayah', 1, NOW(), NOW()),
('199', 'Lain-lain', 'jenayah', 1, NOW(), NOW());

