<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StaffSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            'NOR FAISAL BIN MOHD LEMAN',
            'BURHANUDIN BIN ABDUL HALIM',
            'MOHD HAFIZ BIN RAZALI',
            'MUHAMMAD SUHAILI BIN SAJIMAN',
            'KHAIRUL HAZRI BIN SULAIMAN',
            'NOR MAZWIN BINTI ABDUL SAMMAD',
            'NURHELMI BIN IKHSAN',
            'MUHAMMAD AZINUDDIN SYAZWAN BIN M. THAMRIN',
            'JASLAN BIN ALI',
            'SAHADAN BIN IDRUS',
            'ABDUL RAHMAN BIN HAYAT',
            'MOHD RAFIQ HAZWAN BIN MOHAMAD RUSNIN',
            'AKMALA BT. MD. AMIN',
            'MOHD RADZI BIN SALIMAN',
            'MOHD AKMAL BIN HAJI SENIN',
            'KASRIN BIN YAACOB',
            'ZIL HUSHAM BIN ZAKARIA',
            'ROSLY BIN MOHAMED ARUS',
            'SYUHADA BINTI AHMAD SAIFUDDIN',
            'ALIFF FAZHIN BIN HAMDAN',
            'RAZIMAN SYAH BIN RAHMAT',
            'MOHD GHAZALI BIN MOHAMAD ISMAIL',
            'MARIAH BINTI KABRI',
            'MOHD NORDIN BIN ABDULLAH',
            'MOHD. AZWAN BIN ISMAIL',
            'MOHD. HAIRIL BIN MD. BUSARI',
            'ROLNIJAYAWIRAWAN BIN JAILANI',
            'MOHD AZWAN BIN HAIRUDDIN',
            'SHARIZWAN BIN MOHAMAD SHARIP',
            'SITI NORHAYU BINTI MOHD AMRI',
            'MOHD ZAILANI BIN JUNI',
            'NORAFIZ BIN AHMAD',
            'FIRDAUS BIN AHMAD TARMIZI',
            'MUHAMMAD FAIZUDDIN HILMY BIN SHAMSUDDIN',
            'MOHD NURFAIZ BIN MAD DALILAN',
            'KHAIRIL FIKRI BIN AHMAD PAIMAN',
            'MOHD. KHAIRUL B. MUSA',
            'FARDZUAN HATTA BIN MAT KHODHORI',
            'AHMAD ADNIN AULA BIN MAT ANI',
            'MOHD IZHAR BIN DOLLAH',
            'AHYAR BIN HJ ABDUL RAHMAN',
            'MOHD IDHAM BIN MOHD IDRIS',
            'MOHD SHOHADAK BIN MUZAKIR',
            'MUHAMAD SALEH B. KASRIN',
            'FAHIZAR BIN PAIMAN',
            'ZUL HASYIRIEN BIN AHMAD JAIS',
            'NURHUDA BINTI MUSLIMIN',
            'HANIS ATIRA BINTI MISRAN',
            'MOHD FAIZAL BIN MOHD AZIZ',
            'MOHD MAFAZI ZIL IKRAM BIN MISROL',
            'MUHAMAD ZAIDI BIN HAMZAH',
            'MUHAMMAD SALLEHUDDIN BIN MOHD SA\'AT',
            'MUHAMMAD HARIZ BIN DAMANHURI @ DAMANURI',
            'NURUL ASYIKIN BINTI ABDUL MANAF',
            'SITI MAISARAH BINTI MASRI',
            'AHMAD JANUAR BIN SATARIS',
            'SITI RAHMAH BINTI ANOR',
            'ZAINATUN NAJIHAH BINTI ZAILAINAI',
            'MOHD DZULFADZLIE BIN MAT NOR',
            'NOR SHUHADAH BINTI MUHAMMAD SHARIF',
            'NOR ASHIKIN BT ARSAT',
            'MOHAMED HAFIZ BIN ABD LATIP',
            'NURUL SHAZREENA BINTI KAIMIN',
            'SITI AZATUL AIN BT IBRAHIM',
            'MOHD FAHME BIN AHMAD KAMAL',
            'WAN HASNIDA BT ABDUL HADI',
            'SALLEHUDDIN BIN MOHD SIDEK',
            'SITI ROHAYA AINI BINTI ABDULLAH NAJIB',
            'ZAINORIZZATI BINTI MOHD JALANI',
            'NORMAWADDAH BINTI NOR AZLI',
            'NURUL AINI BINTI MOHD SARBINI',
            'ISMAIL BIN MARUDIN @ NORDIN',
            'ABDUL RASYID BIN HUSSAIN',
            'KHAIRUN NADZRI BIN MOHD SHAKOR',
            'MOHD NAZIM BIN BAHNAN',
            'NOR HAFIZ BIN MOHD LEMAN',
            'MOHD KAIRI BIN SAHUDIN',
            'MOHD FAIZAL BIN NGADIMAN',
            'NURUL AIN BINTI ROSLAN',
            'MOHD AZIZI BIN MOHAMAD SANI',
            'AHMAD FARID BIN ISMAIL',
            'NOOR BAIZURA BINTI ASKUR',
            'ZIZUL NAZIHA BINTI ZULKIFLY',
            'S NORSHAWAL BIN SUYURNO',
            'MOHD SUKRI BIN SAMSUDDIN',
            'MUHAMMAD AZZAM BIN MOHD SALEH',
            'MUHAMMAD ABDUL JAWAD BIN MUHAMED ZAMRI',
            'MOHAMAD AZIZI BIN SATIBI',
            'MOHD FAIRUZ BIN HAMDAN',
            'NOR KHAIRINA ALIZA BINTI HUSIN',
            'SAMSIAH BINTI ABDUL HAMID',
            'MOHD HAFIDZ BIN AHMAN',
            'NAZIZUL BIN MOHAMMED LEHAN',
            'MOHAMMAD MUHAIMIN BIN OSTHAMAN',
            'SITI NOOR FATHEMAH BINTI SAYUTI',
            'MOHAMAD HUSAIRI BIN MOHAMED WILDAN',
            'NUR HIDAYAH BINTI SAMSUDDIN',
            'ARIFF ALFIAN BIN NORAZMAN',
            'NADIAH BINTI HATIM',
            'MOHAMAD ARIF NOR BIN MOHAMAD NAJIB',
            'NUR IZZAH HAZWANI BINTI MOHD AMIN',
            'REZMAN ABDULLAH @ JOHARI BIN MAGITAT',
            'RUZAIDA BINTI ISHAK',
            'FAZA SHA BINTI ZAINUDDIN',
            'MOHAMMAD HAFFIZI BIN MOHAMMAD RUSLAN',
            'MUHAMAD ALIF BIN JAMALI',
            'AHMAD KAMAL BIN MOHAMD',
            'SITI NOOR FAZELIANA BINTI AWALUDIN',
            'MOHD AZRUL EFFENDY BIN BAHRIN',
            'MOHAMMAD HAZIQ HAKIM BIN MOHAMMAD ASRI',
            'MOHD FAIZAL BIN ANUAR',
            'MOHD HANIF BIN OTHMAN',
            'MD ZURAIMI BIN PARDEI',
            'MOHD FAHKRI BIN ALUWI',
            'NORSYAFINA BINTI ABDUL RASIP',
        ];

        foreach ($names as $name) {
            $cleanName = trim(preg_replace('/\s+/', ' ', $name));
            DB::table('staff')->updateOrInsert(
                ['name' => $cleanName],
                [
                    'is_active' => 1,
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
